apiVersion: apps/v1
kind: Deployment

metadata:
  name: lnd

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lnd
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
      - name: lnd
        image: code.liv.io/liv/lnd
        workingDir: /
        ports:
        - name: lnd-network
          containerPort: 9735
          protocol: TCP
        - name: lnd-rest
          containerPort: 8080
          protocol: TCP
        env:
        - name: BITCOIN_NETWORK
          value: "testnet3"
        - name: ALIAS
          value: "liv.io"
        - name: BITCOIND_RPCHOST
          value: "btc-external-latest.btc.svc.cluster.local:18332"
        - name: BITCOIND_RPCPASS
          valueFrom:
            secretKeyRef:
              name: lnd-secrets
              key: BITCOIND_RPCPASS
        - name: BITCOIND_RPCUSER
          value: "satoshi"
        - name: BITCOIND_ZMQPUBRAWBLOCK
          value: "tcp://btc-external-latest.btc.svc.cluster.local:5557"
        - name: BITCOIND_ZMQPUBRAWTX
          value: "tcp://btc-external-latest.btc.svc.cluster.local:5558"
        - name: COLOR
          value: "#00cdfa"
        - name: EXTERNALIP
          value: "213.193.83.252"
        - name: LISTEN
          value: "0.0.0.0:9735"
        - name: RESTLISTEN
          value: "0.0.0.0:8080"
        - name: WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lnd-secrets
              key: WALLET_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsGroup: 10000
          runAsUser: 10000
          seLinuxOptions:
            type: spc_t
        volumeMounts:
        - name: lnd-data
          mountPath: /var/local/lnd/data
      imagePullSecrets:
      - name: code.liv.io
      volumes:
      - name: lnd-data
        persistentVolumeClaim:
          claimName: lnd-pvc
