apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lnd

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - servers-transport.yaml

images:
  - name: code.liv.io/liv/lnd
    newTag: 0.21.1-beta-1
