apiVersion: apps/v1
kind: Deployment

metadata:
  name: btc

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: btc
  template:
    metadata:
      labels:
        app: btc
    spec:
      containers:
      - name: bitcoin-core
        image: code.liv.io/liv/bitcoin-core
        workingDir: /
        ports:
        - name: btc-network
          containerPort: 18333
          protocol: TCP
        - name: btc-rpc
          containerPort: 18332
          protocol: TCP
        - name: btc-zmqphblock
          containerPort: 5555
          protocol: TCP
        - name: btc-zmqphtx
          containerPort: 5556
          protocol: TCP
        - name: btc-zmqprblock
          containerPort: 5557
          protocol: TCP
        - name: btc-zmqprtx
          containerPort: 5558
          protocol: TCP
        env:
        - name: CHAIN
          value: "testnet3"
        - name: MAXUPLOADTARGET
          value: "12000"
        - name: DBCACHE
          value: "512"
        - name: PORT
          value: "18333"
        - name: RPCPORT
          value: "18332"
        - name: REST
          value: "True"
        - name: RPCALLOWIP
          value: "0.0.0.0/0"
        - name: RPCAUTH
          valueFrom:
            secretKeyRef:
              name: btc-secrets
              key: RPCAUTH
        - name: RPCBIND
          value: "0.0.0.0"
        - name: RPCWORKQUEUE
          value: "64"
        - name: ZMQPUBHASHBLOCK
          value: "tcp://0.0.0.0:5555"
        - name: ZMQPUBHASHTX
          value: "tcp://0.0.0.0:5556"
        - name: ZMQPUBRAWBLOCK
          value: "tcp://0.0.0.0:5557"
        - name: ZMQPUBRAWTX
          value: "tcp://0.0.0.0:5558"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsGroup: 10000
          runAsUser: 10000
          seLinuxOptions:
            type: spc_t
        volumeMounts:
        - name: btc-db
          mountPath: /var/local/bitcoin-core/db
      imagePullSecrets:
      - name: code.liv.io
      volumes:
      - name: btc-db
        persistentVolumeClaim:
          claimName: btc-pvc
