apiVersion: v1
kind: Service

metadata:
  name: int

spec:
  type: ClusterIP
  ports:
  - name: network
    port: 18333
    targetPort: network
    protocol: TCP
  - name: zmqphblock
    port: 5555
    targetPort: zmqphblock
    protocol: TCP
  - name: zmqphtx
    port: 5556
    targetPort: zmqphtx
    protocol: TCP
  selector:
    app: btc

---

apiVersion: v1
kind: Service

metadata:
  name: ext

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: rpc
    port: 18332
    targetPort: rpc
    protocol: TCP
  - name: zmqprblock
    port: 5557
    targetPort: zmqprblock
    protocol: TCP
  - name: zmqprtx
    port: 5558
    targetPort: zmqprtx
    protocol: TCP
  selector:
    app: btc
